### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by tembokk** [nvim-neorocks/rocks.nvim#166] opened 2024-02-27 14:56 UTC
My nvim version: `v0.10.0-dev-2388+gb12d193b4` 
I install `lua` and `luarocks` through `scoop install lua-for-windows`
Then on rocks.nvim installation I set `Set up luarocks (recommended) ?:` **`false`**
And I get this error 
```
Installing rocks.nvim...
E5108: Error executing lua: ...m-nightly\current\share\nvim\runtime/lua/vim/_system.lua:241: ENOENT: no such file or directory
stack traceback:
	[C]: in function 'error'
	...m-nightly\current\share\nvim\runtime/lua/vim/_system.lua:241: in function 'spawn'
	...m-nightly\current\share\nvim\runtime/lua/vim/_system.lua:332: in function 'system'
	C:\Users\Windows 10\AppData\Local\Temp\nvim.0\ywhunR\0.lua:383: in function <C:\Users\Windows 10\AppData\Local\Temp\nvim.0\ywhunR\0.lua:357>
```

**Comment by mrcjkb** [comment] 2024-02-28 07:04
Which version of luarocks does scoop install and what's the output of `luarocks --version` on the command line?

**Comment by mrcjkb** [comment] 2024-02-28 16:26
Thanks for troubleshooting this!

I've looked at the neovim source. `vim.system` uses `uv.spawn` under the hood, which says:

>  Possible reasons for failing to spawn would include (but not be limited to) the
> file to execute not existing, not having permissions to use the setuid or setgid
> specified, or not having enough memory to allocate for the new process.

and can confirm that `ENOENT: no such file or directory` is thrown when you pass in a binary it can't find.

Regarding: `Lua 5.1 interpreter not found in $PATH`:

We use `sh configure` to configure luarocks. My guess is that it falls back to `git sh` on Windows (I don't think `sh` is installed by default, but git for Windows installs it iirc?). So it's likely that `git sh` doesn't see the `PATH`.

@vhyrro What do you think? Maybe we should use `vim.o.sh` for this?
@tembokk What's the output of `:lua =vim.o.sh` on your Windows machine?

luarocks 2.0.2 is very outdated and unlikely to work with rocks.nvim (we should probably add a minimum version requirement check to the installer).

> `Error: Failed finding Lua header files. You may need to install them or configure LUA_INCDIR.`

Are you still using lua installed with `scoop`? luarocks makes some assumptions about where to find header files.

Now that I think of it, even if you fix the issue with luarocks not finding lua, you'll probably run into issues installing one of rocks.nvim's dependencies, `toml-edit.lua`.
We [haven't yet succeeded in building it for Windows with GitHub actions](https://github.com/nvim-neorocks/rocks-binaries/actions/runs/7918737290/job/21617883179).

**Comment by mrcjkb** [comment] 2024-03-04 07:51
> > What's the output of :lua =vim.o.sh on your Windows machine?
> 
> In my config I set it to `pwsh` but with `nvim -u NORC` it's `cmd.exe`
> 
> > Are you still using lua installed with scoop?
> 
> I plan to stick to `hererocks` from now on

Would you be able to test if using `vim.o.sh` works for you?
We'll probably have some more stuff to iron out for Windows (a fix for the toml-edit binary rock is in the pipeline).

> but with nvim -u NORC it's cmd.exe

We recommend to use `nvim -u NORC`, as plugins like oil.nvim can interfere with the installer.

**Comment by mrcjkb** [comment] 2024-03-05 11:27
> > Would you be able to test if using vim.o.sh works for you?
> > I'll try to test outside neovim first
> 
> It seems hererocks act differently with and without admin priviliges. Probably this is an issue on `scoop`, since I also installed python from `scoop`.
> 
> Without admin privileges
> With admin privileges

This is the toml-edit dependeny issue I mentioned earlier, for which we have a fix in the pipeline.
I'll let you know when it's ready.

@vhyrro could you trigger the luarocks upload workflow for toml-edit manually? It looks like the last run failed with an API error.

**Comment by mrcjkb** [comment] 2024-03-07 20:00
> I think the problem is fzy
> 
> > With admin privileges
> > ```
> > fzy 1.0-1 depends on lua >= 5.1 (5.1-1 provided by VM)
> > C:\Users\Windows 10\scoop\apps\mingw\current\bin\gcc.exe -O2 -c -o src/fzy_native.o -IC:\Users\Windows 10\Downloads\executable\luarocks\include src/fzy_native.c -DLUA_COMPAT_5_1
> > 'C:\Users\Windows' is not recognized as an internal or external command, operable program or batch file.
> > 
> > Error: Failed installing dependency: https://luarocks.org/fzy-1.0-1.src.rock - Build error: Failed compiling object src/fzy_native.o
> > ```

That's strange. I think fzy needs [MVSC](https://visualstudio.microsoft.com/vs/features/cplusplus/) to be installed, so that you can build it on Windows.
But we also fail to build it for our rocks-binaries server, because Windows is missing a header file. I've opened an issue for that: https://github.com/swarn/fzy-lua/issues/11

**Comment by mrcjkb** [comment] 2024-03-10 17:57
That error is caused by luarocks trying to compile fzy, which is strange, because the rocks.nvim installer should tell luarocks to fetch it from a binary server.

Are you able to run

```
luarocks --server='https://nvim-neorocks.github.io/rocks-binaries/ --local fzy
```

?

It could be that luarocks doesn't fetch the `win32-x86_64.rock` if it detects your platform as `mingw32`, in which case it will try to compile it from source.

I believe if you run `luarocks config`, it should output your config, with an `arch` value that tells you what platform it thinks you're on.

**Comment by mrcjkb** [comment] 2024-03-10 18:12
Hmm, based on your config it appears to be the correct architecture.

Are you able to run `luarocks --server='https://nvim-neorocks.github.io/rocks-binaries/' --local install fzy`?

**Comment by mrcjkb** [comment] 2024-03-10 18:37
> But when I try to do luarocks install rocks.nvim, it still says that fzy is not installed

That's because when you run luarocks as an admin, and when you run luarocks as non-admin (with the `--local` flag), it installs packages to different locations.

If you can install `fzy` with the `--server` configuration, you should also be able to run

```
luarocks --server='https://nvim-neorocks.github.io/rocks-binaries/' --local install rocks.nvim
```

... but this will install rocks.nvim and its dependencies to a different location than rocks.nvim expects (it uses the `--tree` flag when invoking luarocks to specify the install directory).

I've pushed the `vim.o.sh` fix to the installer. Can you try

```
nvim -u NORC -c "source https://raw.githubusercontent.com/nvim-neorocks/rocks.nvim/master/installer.lua"
```

again?

**Comment by mrcjkb** [comment] 2024-03-10 19:50
Ah, I think I know what's happening.
The installer tells you to set the paths for Linux binaries.

I think if you change `?.so` to `?.dll` in the `luarocks_cpath` patterns, it should work.

**Comment by mrcjkb** [comment] 2024-03-10 21:57
Oof, that's going to be hard for me to troubleshoot without a Windows machine.

I suppose you could go into the rocks.nvim installation and try to comment out parts of the [plugin/rocks.lua](https://github.com/nvim-neorocks/rocks.nvim/blob/master/plugin/rocks.lua#L6) file, so we can get an idea when it is crashing.

Thanks for all the patience by the way 🙏

**Comment by mrcjkb** [comment] 2024-03-24 21:27
I've added a GitHub action for Windows, and can reproduce the crash.

https://github.com/nvim-neorocks/rocks.nvim/actions/runs/8412208971/job/23032769269?pr=224

It appears to crash before the log file is created.

**Comment by mrcjkb** [comment] 2024-03-24 22:16
:thinking: it looks like it could be crashing even without rocks.nvim (at least my test command isn't printing to stdout [note: I have to redirect stderr because neovim prints to stderr]).

@tembokk are you able to run neovim nightly on Windows?

**Comment by mrcjkb** [comment] 2024-03-25 16:54
Update: I fixed the init.lua I was using to test, and can [confirm it segfaults on Windows](https://github.com/nvim-neorocks/rocks.nvim/actions/runs/8423789928/job/23066226716?pr=224).

Now for the difficult task of finding out why...

**Comment by mrcjkb** [comment] 2024-03-25 21:55
I've tracked down the segfault to a `require("toml")` call.
It doesn't happen with another library (`require("toml_edit")`), so I think this is a [toml.lua](https://github.com/LebJe/toml.lua) bug.

**Comment by mrcjkb** [comment] 2024-04-02 06:01
> Thank you! So I just need to wait for that PR to be merged right?

Yes, hopefully that should be the last hurdle.
I've set up a GitHub action with a basic integration test for Windows, so I'll see after it's merged if there's anything else.

**Comment by mrcjkb** [comment] 2024-04-07 13:49
@tembokk I've removed the `toml` dependency from the latest release.
My Windows test on GitHub Actions isn't working yet, but you could give it another try.

**Comment by mrcjkb** [comment] 2024-04-07 15:54
[My basic windows integration test just succeeded](https://github.com/nvim-neorocks/rocks.nvim/actions/runs/8589893019/job/23536678567) :rocket:

**Closed by mrcjkb** 2024-04-07 15:54 UTC
Labels: enhancement

**Comment by mrcjkb** [comment] 2024-04-07 16:06
I've created a separate issue for the installer script: https://github.com/nvim-neorocks/rocks.nvim/issues/255
