### ISSUE TITLE
Can't build tree-sitter-<lang> on alpine

### ISSUE THREAD

**Issue by quadraplat** [nvim-neorocks/rocks.nvim#580] opened 2024-11-01 13:43 UTC
When setting up rocks.nvim on a new system with alpine I could not build any tree-sitter-<lang> plugins. I set it up to not point to a server so I could build plugins on device and avoid glibc issues.

After failing to build any tree-sitter highlighters, I reinstalled rocks.nvim and tried to install a tree-sitter highligter. On first run, this gave me the following error in `:Rocks log`.
```
[START][2024-11-01 14:35:34] rocks.nvim logging initiated
ERROR | 2024-11-01 14:35:57 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:65 |        luarocks CLI FAILED
ERROR | 2024-11-01 14:35:57 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:66 |
Error: Failed installing dependency: https://luarocks.org/luarocks-build-treesitter-parser-5.0.2-1.src.rock - Failed installing dependency: https://luarocks.org/luafilesystem-1.8.0-1.src.rock - Build error: Failed finding Lua header lua.h (searched at /usr/include/lua/5.4). You may need to install Lua development headers. You can use `luarocks config variables.LUA_INCDIR <path>` to set the correct location.

ERROR | 2024-11-01 14:35:57 | ...im/rocks/rocks_rtp/lua/rocks/operations/helpers/init.lua:104 |       Failed to install tree-sitter-cpp
```
This is odd, since it complains about missing lua5.4, which I wouldn't think I would need since neovim uses luajit
On trying to install a tree-sitter highlighter again I get a different error
```
[START][2024-11-01 14:42:07] rocks.nvim logging initiated
ERROR | 2024-11-01 14:42:25 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:65 | luarocks CLI FAILED
ERROR | 2024-11-01 14:42:25 | ....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:66 | 
Error: LuaRocks 3.11.1 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
.../.local/share/nvim/rocks/share/lua/5.1/luarocks/deps.lua:242: assertion failed!
stack traceback:
	[C]: in function 'assert'
	.../.local/share/nvim/rocks/share/lua/5.1/luarocks/deps.lua:242: in function 'luarocks.deps.fulfill_dependency'
	.../.local/share/nvim/rocks/share/lua/5.1/luarocks/deps.lua:335: in function 'luarocks.deps.fulfill_dependencies'
	(...tail calls...)
	....local/share/nvim/rocks/share/lua/5.1/luarocks/build.lua:416: in function 'luarocks.build.build_rockspec'
	...al/share/nvim/rocks/share/lua/5.1/luarocks/cmd/build.lua:74: in function <...al/share/nvim/rocks/share/lua/5.1/luarocks/cmd/build.lua:51>
	(...tail calls...)
	...al/share/nvim/rocks/share/lua/5.1/luarocks/cmd/build.lua:159: in function 'luarocks.cmd.build.command'
	(...tail calls...)
	.../.local/share/nvim/rocks/share/lua/5.1/luarocks/deps.lua:236: in function 'luarocks.deps.fulfill_dependency'
	.../.local/share/nvim/rocks/share/lua/5.1/luarocks/deps.lua:335: in function 'luarocks.deps.fulfill_dependencies'
	....local/share/nvim/rocks/share/lua/5.1/luarocks/build.lua:139: in upvalue 'process_dependencies'
	....local/share/nvim/rocks/share/lua/5.1/luarocks/build.lua:416: in function 'luarocks.build.build_rockspec'
	...al/share/nvim/rocks/share/lua/5.1/luarocks/cmd/build.lua:74: in function <...al/share/nvim/rocks/share/lua/5.1/luarocks/cmd/build.lua:51>
	(...tail calls...)
	...al/share/nvim/rocks/share/lua/5.1/luarocks/cmd/build.lua:159: in function 'luarocks.cmd.build.command'
	(...tail calls...)
	[C]: in function 'xpcall'
	...s/.local/share/nvim/rocks/share/lua/5.1/luarocks/cmd.lua:765: in function 'luarocks.cmd.run_command'
	...ks/lib/luarocks/rocks-5.1/luarocks/3.11.1-1/bin/luarocks:35: in main chunk
	[C]: in ?

ERROR | 2024-11-01 14:42:25 | ...im/rocks/rocks_rtp/lua/rocks/operations/helpers/init.lua:104 | Failed to install tree-sitter-cpp
```

Not sure this is an issue with using alpine, a luarocks issue or a rocks.nvim issue.

**Comment by quadraplat** [comment] 2024-11-01 14:46
tried reinstalling rocks.nvim with lua5.4-dev installed, this time I get the same error message as #579, so this might be a duplicate.

**Comment by mrcjkb** [comment] 2024-11-01 17:21
Hey :wave: 

Yes, you need the Lua headers (which are not shipped with Neovim) to compile native Lua libraries.

Closing as duplicate of #579.

**Closed by mrcjkb** 2024-11-01 17:21 UTC

**Comment by quadraplat** [comment] 2024-11-08 15:29
I manged to solve the issue by installing lua5.4-devel, but I though I would need lua5.1, but 5.4
