### ISSUE TITLE
`toml` dependency causes segfault (neovim crash)

### ISSUE THREAD

**Issue by tarcisioe** [nvim-neorocks/rocks.nvim#228] opened 2024-03-27 21:38 UTC
Output of `nvim -v`:

```
NVIM v0.10.0-dev-2718+g1bfe6fdceb
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
Run "nvim -V1 -v" for more info
```

I'm on arch-linux with neovim installed using `neovim-git` from the AUR. Neovim closes unless I comment out the line `vim.opt.runtimepath:append(vim.fs.joinpath(rocks_config.rocks_path, "lib", "luarocks", "rocks-5.1", "rocks.nvim", "*"))`. I removed everything else from my `init.lua`. No plugins were even installed yet.

`nvim --startuptime` seems to indicate Neovim is exiting way earlier than it should:

```
--- Startup times for process: Primary/TUI ---

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.002  000.002: --- NVIM STARTING ---
000.946  000.944: event init
001.219  000.273: early init
001.368  000.148: locale set
001.635  000.267: init first window
002.742  001.107: inits 1
002.769  000.027: window checked
002.778  000.009: parsing arguments
004.878  000.109  000.109: require('vim.shared')
005.168  000.128  000.128: require('vim.inspect')
005.436  000.228  000.228: require('vim._options')
005.445  000.553  000.197: require('vim._editor')
005.449  000.784  000.121: require('vim._init_packages')
005.454  001.892: init lua interpreter
009.883  004.428: expanding arguments
010.004  000.121: inits 2
010.768  000.764: init highlight
010.777  000.009: --- NVIM STARTED ---
```

`nvim --clean --startuptime` shows logs for a second process ("Embedded"):

```
--- Startup times for process: Primary/TUI ---

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.001  000.001: --- NVIM STARTING ---
000.437  000.436: event init
000.741  000.304: early init
000.842  000.101: locale set
000.982  000.140: init first window
001.619  000.637: inits 1
001.641  000.022: window checked
001.652  000.011: parsing arguments
002.780  000.078  000.078: require('vim.shared')
003.023  000.123  000.123: require('vim.inspect')
003.164  000.102  000.102: require('vim._options')
003.171  000.381  000.157: require('vim._editor')
003.174  000.509  000.050: require('vim._init_packages')
003.179  001.018: init lua interpreter
004.653  001.474: expanding arguments
004.716  000.063: inits 2
005.280  000.564: init highlight
005.286  000.006: --- NVIM STARTED ---

--- Startup times for process: Embedded ---

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.001  000.001: --- NVIM STARTING ---
001.096  001.094: event init
001.337  000.241: early init
001.450  000.113: locale set
001.558  000.108: init first window
002.093  000.535: inits 1
002.123  000.030: window checked
002.132  000.009: parsing arguments
003.355  000.109  000.109: require('vim.shared')
003.508  000.077  000.077: require('vim.inspect')
003.626  000.094  000.094: require('vim._options')
003.633  000.270  000.099: require('vim._editor')
003.637  000.517  000.138: require('vim._init_packages')
003.642  000.993: init lua interpreter
004.033  000.392: expanding arguments
004.085  000.052: inits 2
004.731  000.646: init highlight
004.735  000.004: waiting for UI
005.053  000.318: done waiting for UI
005.076  000.023: clear screen
005.186  000.021  000.021: require('vim.keymap')
007.100  000.887  000.887: require('vim.termcap')
007.392  000.104  000.104: require('vim.text')
007.534  002.449  001.437: require('vim._defaults')
007.540  000.015: init default mappings & autocommands
007.908  000.164  000.164: sourcing /usr/share/nvim/runtime/ftplugin.vim
008.106  000.088  000.088: sourcing /usr/share/nvim/runtime/indent.vim
008.125  000.333: sourcing vimrc file(s)
008.438  000.254  000.254: sourcing /usr/share/nvim/runtime/filetype.lua
008.913  000.180  000.180: sourcing /usr/share/nvim/runtime/syntax/synload.vim
009.262  000.701  000.521: sourcing /usr/share/nvim/runtime/syntax/syntax.vim
010.620  000.369  000.369: sourcing /usr/share/nvim/runtime/plugin/gzip.vim
012.366  000.676  000.676: sourcing /usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
012.524  001.749  001.072: sourcing /usr/share/nvim/runtime/plugin/matchit.vim
012.849  000.258  000.258: sourcing /usr/share/nvim/runtime/plugin/matchparen.vim
013.606  000.699  000.699: sourcing /usr/share/nvim/runtime/plugin/netrwPlugin.vim
013.784  000.092  000.092: sourcing /usr/share/nvim/runtime/plugin/rplugin.vim
013.965  000.123  000.123: sourcing /usr/share/nvim/runtime/plugin/shada.vim
014.080  000.040  000.040: sourcing /usr/share/nvim/runtime/plugin/spellfile.vim
014.428  000.222  000.222: sourcing /usr/share/nvim/runtime/plugin/tarPlugin.vim
014.570  000.066  000.066: sourcing /usr/share/nvim/runtime/plugin/tutor.vim
015.006  000.350  000.350: sourcing /usr/share/nvim/runtime/plugin/zipPlugin.vim
015.245  000.151  000.151: sourcing /usr/share/nvim/runtime/plugin/editorconfig.lua
015.533  000.203  000.203: sourcing /usr/share/nvim/runtime/plugin/man.lua
015.715  000.113  000.113: sourcing /usr/share/nvim/runtime/plugin/nvim.lua
015.989  000.215  000.215: sourcing /usr/share/nvim/runtime/plugin/osc52.lua
016.137  000.084  000.084: sourcing /usr/share/nvim/runtime/plugin/tohtml.lua
016.178  002.365: loading rtp plugins
016.348  000.170: loading packages
016.764  000.416: loading after plugins
016.792  000.029: inits 3
016.805  000.013: reading ShaDa
016.974  000.169: opening buffers
017.045  000.071: BufEnter autocommands
017.053  000.008: editing files in windows
017.224  000.171: VimEnter autocommands
017.231  000.007: UIEnter autocommands
017.233  000.003: before starting main loop
017.965  000.732: first screen update
017.970  000.005: --- NVIM STARTED ---
```

**Comment by tarcisioe** [comment] 2024-03-27 21:55
Tracing the error by returning early from the called modules, it seems something happens while `toml.decode` is being called. I'm getting return code 132, which apparently indicates that Neovim was killed by signal 4 meaning "Illegal Instruction", but I'm running it on a x86_64 VPS.

**Comment by mrcjkb** [comment] 2024-03-27 22:02
Hey :wave: 

Thanks for reporting.
We've discovered the same segfault caused by the `toml` dependency on Windows (see https://github.com/nvim-neorocks/rocks.nvim/issues/166#issuecomment-2018987679).

Once https://github.com/vhyrro/toml-edit.lua/pull/13 has been merged and released, we can remove the `toml` dependency.

**Comment by mrcjkb** [comment] 2024-03-27 22:07
> Indeed it seems my toml.so is somehow borked:

It's strange that you're experiencing it on Arch Linux.
I haven't had any problems with it on NixOS (the same architecture).

**Comment by tarcisioe** [comment] 2024-03-27 22:58
> It's strange that you're experiencing it on Arch Linux. I haven't had any problems with it on NixOS (the same architecture).

It seems that the issue is that the VPS I'm running Neovim on uses an old Intel Xeon (circa 2012). The prebuilt binary for toml.so seems to use some newer instruction that isn't supported by the CPU. I worked around the issue by building toml.lua there and swapping `toml.so`.

I find it a bit strange that the prebuilt binary uses something specific that makes it not so generic, but I guess 2012 was indeed a long time ago.

**Comment by mrcjkb** [comment] 2024-03-27 23:03
That is indeed strange But if toml was the only package causing problems for you, it'll be solved when we remove it :smile:

**Comment by tarcisioe** [comment] 2024-03-27 23:06
> That is indeed strange But if toml was the only package causing problems for you, it'll be solved when we remove it 😄

Seems so, rocks worked nicely after swapping! This isn't the machine I mainly use vim on also, so not an urgent issue. I think this can be closed.

**Comment by mrcjkb** [comment] 2024-03-27 23:15
Thanks again for the thorough investigation :smile:

**Comment by mrcjkb** [comment] 2024-04-03 15:46
Reopening as this is taking longer than expected

**Comment by mrcjkb** [comment] 2024-04-04 18:36
@tarcisioe we are in the process of adding the capabilities from toml.lua to toml-edit.lua (which we depend on anyway).
Once we've ironed out some build issues, we will be removing the toml.lua dependency from rocks.nvim.

**Comment by Tvrt1e** [comment] 2024-04-04 18:38
@tarcisioe I experienced this on an intel i5 3570 which was also released in 2012.

**Closed** 2024-04-07 11:50 UTC
