### ISSUE TITLE
Installation script failed (luarocks, termux)

### ISSUE THREAD

**Issue by xiaoshihou514** [nvim-neorocks/rocks.nvim#544] opened 2024-09-21 00:53 UTC
I am aware of #539, but in the mean time, I have some issues bootstraping luarocks on `termux`.
![Screenshot_2024-09-21-08-34-37-143_com.termux.jpg](https://github.com/user-attachments/assets/0c35fb8d-44e5-4a52-923d-502b16aca943)
If I try copying out `sysdetect.lua` and call the detect function (luajit), it will actually give me somewhat accurate output (sysv, aarch64). It's likely a bug in luarocks, but:
- a. I will put it here for reference
- b. Question: how did the installation script bootstrap luarocks? Through `make`? I am trying to fix this but I need more context.
Thank you!

**Comment by mrcjkb** [comment] 2024-09-21 06:08
Duplicate of #208.

> Question: how did the installation script bootstrap luarocks? Through make?

Yes.

**Closed by mrcjkb** 2024-09-21 06:08 UTC

**Comment by xiaoshihou514** [comment] 2024-09-21 09:51
Followup: rocks.nvim won't work on termux as android apps are prohibited to use hard links, which rocks.nvim currently uses when performing a sync.

**Comment by mrcjkb** [comment] 2024-09-21 09:57
rocks.nvim should be creating soft links.
And it will only fail if you're using a fat32 filesystem, which to my knowledge is not the case for all Android systems.

**Comment by mrcjkb** [comment] 2024-09-21 09:57
locking this issue as it's a duplicate.
