### ISSUE TITLE
module 'luarocks.core.cfg' not found:

### ISSUE THREAD

**Issue by boydkelly** [nvim-neorocks/rocks.nvim#461] opened 2024-07-06 09:43 UTC
I've been getting this for a while on startup(and other commands, h for example).   I endedup totally nuking my .local/share/nvim and letting nvim-rocks reinstall with the same results.   I'm suspicous that maybe since Fedora is packaged with lua 5.4 and below is running /usr/bin/luajit from the os,  that is where the problem may be...  Any further suggestions/hints for troubleshooting this? Thanks!!

````
   Error  09:32:07 msg_show.lua_error Error executing vim.schedule lua callback: ...elly/.local/share/nvim/rocks/share/lua/5.1/nio/tasks.lua:100: Async task failed without callback: The coroutine failed with this message: 
...ly/.local/share/nvim/rocks/share/lua/5.1/nio/control.lua:145: /usr/bin/luajit: ...ks/lib/luarocks/rocks-5.1/luarocks/3.11.1-1/bin/luarocks:4: module 'luarocks.core.cfg' not found:
	no field package.preload['luarocks.core.cfg']
	no file '/run/user/1000/luarocks-B3747462C073A0/share/lua/5.1/luarocks/core/cfg.lua'
	no file './luarocks/core/cfg.lua'
	no file '/usr/share/luajit-2.1/luarocks/core/cfg.lua'
	no file '/usr/local/share/lua/5.1/luarocks/core/cfg.lua'
	no file '/usr/local/share/lua/5.1/luarocks/core/cfg/init.lua'
	no file '/usr/share/lua/5.1/luarocks/core/cfg.lua'
	no file '/usr/share/lua/5.1/luarocks/core/cfg/init.lua'
	no file '/var/home/bkelly/.luarocks/share/lua/5.1/luarocks/core/cfg.lua'
	no file '/var/home/bkelly/.luarocks/share/lua/5.1/luarocks/core/cfg/init.lua'
	no file '/run/user/1000/luarocks-B3747462C073A0/share/lua/5.1/luarocks/core/cfg/init.lua'
	no file './luarocks/core/cfg.so'
	no file '/usr/local/lib/lua/5.1/luarocks/core/cfg.so'
	no file '/usr/lib64/lua/5.1/luarocks/core/cfg.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/var/home/bkelly/.luarocks/lib/lua/5.1/luarocks/core/cfg.so'
	no file '/run/user/1000/luarocks-B3747462C073A0/lib/lua/5.1/luarocks/core/cfg.so'
	no file './luarocks.so'
	no file '/usr/local/lib/lua/5.1/luarocks.so'
	no file '/usr/lib64/lua/5.1/luarocks.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/var/home/bkelly/.luarocks/lib/lua/5.1/luarocks.so'
	no file '/run/user/1000/luarocks-B3747462C073A0/lib/lua/5.1/luarocks.so'
stack traceback:
	[C]: in function 'require'
	...ks/lib/luarocks/rocks-5.1/luarocks/3.11.1-1/bin/luarocks:4: in main chunk
	[C]: at 0x5625b62c40a0

stack traceback:
	[C]: in function 'error'
	...ly/.local/share/nvim/rocks/share/lua/5.1/nio/control.lua:145: in function 'wait'
	...ly/.local/share/nvim/rocks/rocks_rtp/lua/rocks/state.lua:44: in function 'installed_rocks'
	.../.local/share/nvim/rocks/share/lua/5.1/rocks/adapter.lua:104: in function 'init_site_symlinks'
	.../.local/share/nvim/rocks/share/lua/5.1/rocks/adapter.lua:133: in function 'init_site_links'
	.../.local/share/nvim/rocks/share/lua/5.1/rocks/adapter.lua:138: in function 'init'
	.../luarocks/rocks-5.1/rocks.nvim/2.32.1-1/plugin/rocks.lua:56: in function <.../luarocks/rocks-5.1/rocks.nvim/2.32.1-1/plugin/rocks.lua:55>
stack traceback:
	[C]: in function 'error'
	...elly/.local/share/nvim/rocks/share/lua/5.1/nio/tasks.lua:100: in function 'close_task'
	...elly/.local/share/nvim/rocks/share/lua/5.1/nio/tasks.lua:122: in function 'cb'
	...elly/.local/share/nvim/rocks/share/lua/5.1/nio/tasks.lua:188: in function 'waiter'
	...ly/.local/share/nvim/rocks/share/lua/5.1/nio/control.lua:116: in function 'wake'
	...ly/.local/share/nvim/rocks/share/lua/5.1/nio/control.lua:137: in function 'set_error'
	...ly/.local/share/nvim/rocks/rocks_rtp/lua/rocks/state.lua:38: in function 'on_exit'
	....local/share/nvim/rocks/rocks_rtp/lua/rocks/luarocks.lua:68: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
09:32:10 msg_showcmd :
````

**Comment by mrcjkb** [comment] 2024-07-06 09:52
Potential duplicate of https://github.com/nvim-neorocks/rocks.nvim/issues/397?

**Comment by boydkelly** [comment] 2024-07-06 11:10
working now!   thanks!!!!

**Closed** 2024-07-06 11:10 UTC
