### ISSUE TITLE
Bug: toml wrong architecture   

### ISSUE THREAD

**Issue by ccaglak** [nvim-neorocks/rocks.nvim#172] opened 2024-03-01 15:54 UTC
Error executing Lua callback: ...oguz/.local/share/nvim/rocks/share/lua/5.1/nio/tasks.lua:95: Async task failed without callback: The coroutine failed with this mess
age:                                                                                                                                                                 
error loading module 'toml_edit' from file '/Users/oguz/.local/share/nvim/rocks/lib/lua/5.1/toml_edit.so':                                                           
        dlopen(/Users/oguz/.local/share/nvim/rocks/lib/lua/5.1/toml_edit.so, 6): no suitable image found.  Did find:                                                 
        /Users/oguz/.local/share/nvim/rocks/lib/lua/5.1/toml_edit.so: mach-o, but wrong architecture                                                                 
        /Users/oguz/.local/share/nvim/rocks/lib/lua/5.1/toml_edit.so: mach-o, but wrong architecture                                                                 
stack traceback:                                                                                                                                                     
        [C]: in function 'require'                                                                                                                                   
        ...ocal/share/nvim/rocks/share/lua/5.1/rocks/operations.lua:115: in function 'parse_rocks_toml'                                                              
        ...ocal/share/nvim/rocks/share/lua/5.1/rocks/operations.lua:524: in function <...ocal/share/nvim/rocks/share/lua/5.1/rocks/operations.lua:509>               
stack traceback:                                                                                                                                                     
        [C]: in function 'error'                                                                                                                                     
        ...oguz/.local/share/nvim/rocks/share/lua/5.1/nio/tasks.lua:95: in function 'close_task'                                                                     
        ...oguz/.local/share/nvim/rocks/share/lua/5.1/nio/tasks.lua:117: in function 'step'                                                                          
        ...oguz/.local/share/nvim/rocks/share/lua/5.1/nio/tasks.lua:145: in function 'run'                                                                           
        ...ocal/share/nvim/rocks/share/lua/5.1/rocks/operations.lua:509: in function 'update'                                                                        
        ....local/share/nvim/rocks/share/lua/5.1/rocks/commands.lua:98: in function 'impl'                                                                           
        ....local/share/nvim/rocks/share/lua/5.1/rocks/commands.lua:181: in function <....local/share/nvim/rocks/share/lua/5.1/rocks/commands.lua:172>

**Comment by mrcjkb** [comment] 2024-03-01 16:16
Hey 👋 

Thanks for reporting. Could you please provide some more context?

- [ ] Your operating system/version + architecture

**Comment by mrcjkb** [comment] 2024-03-01 19:03
Thanks.

Note to self: It's probably caused by: https://github.com/nvim-neorocks/rocks-binaries/commit/2b2256ff6056628936e38100e4d323824f7092ad

I guess the m1 binary replaces the x86_64 one.

**Comment by mrcjkb** [comment] 2024-03-01 19:52
See also: https://github.com/luarocks/luarocks/issues/1630

We can probably work around this in the rocks-binaries repo for now.

**Comment by mrcjkb** [comment] 2024-03-01 21:26
@ccaglak I've implemented a workaround for the luarocks bug that caused the issue to our rocks-binaries server. If you reinstall rocks.nvim and its dependencies (toml-edit), it should be fixed.

I think running `:Rocks install rocks.nvim` should reinstall everything (not 100 % sure).

**Comment by ccaglak** [comment] 2024-03-02 10:07
thanks i'll give it try

**Closed** 2024-03-02 23:28 UTC
