### ISSUE TITLE
[BUG] Breaking change in luarocks cmdline interface

### ISSUE THREAD

**Issue by xiaoshihou514** [nvim-neorocks/rocks.nvim#343] opened 2024-05-18 12:33 UTC
`:Rocks log`
```
ERROR | 2024-05-18 13:31:15 | ....local/share/nvim/rocks/share/lua/5.1/rocks/luarocks.lua:66 | luarocks CLI FAILED
ERROR | 2024-05-18 13:31:15 | ....local/share/nvim/rocks/share/lua/5.1/rocks/luarocks.lua:67 | Usage: luarocks [-h] [--version] [--dev] [--server <server>]
       [--only-server <server>] [--only-sources <url>]
       [--namespace <namespace>] [--lua-dir <prefix>]
       [--lua-version <ver>] [--tree <tree>] [--local] [--global]
       [--no-project] [--verbose] [--timeout <seconds>] [<command>]
       ...

Error: unknown option '--force-lock'\
```
```
❯ ./rocks/bin/luarocks --version
./rocks/bin/luarocks dev
LuaRocks main command-line interface
```

**Comment by vhyrro** [comment] 2024-05-18 12:55
Yeah we're aware of this being a problem. The easiest fix is to remove `~/.local/share/nvim/rocks` and rerun the installation script.

In order to prevent such things from happening in the future we're planning on pinning the version of luarocks we're using and also working on a more consistent bootstrapping strategy - sorry in the meantime! :)

**Comment by mrcjkb** [comment] 2024-05-18 13:03
Closing as duplicate of #336

**Closed by mrcjkb** 2024-05-18 13:03 UTC
